config/routes.rb
GhInventoryTracker::Application.routes.draw do
  resources :mounted_inventories

  root :to => "inventory_checks#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :inventory_checks

  
  
  devise_for :users
  ActiveAdmin.routes(self)

  devise_scope :users do
    get "login",    to: "devise/sessions#new"
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
  end

 
end

app/models/mounted_inventory.rb
class MountedInventory < ActiveRecord::Base
  attr_accessible :lot_number, :total_mg, :user_id

  belongs_to :user

  validates :lot_number, :total_mg, :user_id, presence: true
end

app/controllers/mounted_inventories_controller.rb
class MountedInventoriesController < ApplicationController
  before_filter :authenticate_user!
  # before_action :set_mounted_inventory, only: [:show, :edit, :update, :destroy]

  # GET /mounted_inventories
  # GET /mounted_inventories.json
  def index
    @mounted_inventories = MountedInventory.all
    @mounted_inventory = MountedInventory.new
    respond_to do |format|
      format.html
    end
  end

  # GET /mounted_inventories/1
  # GET /mounted_inventories/1.json
  def show
    @mounted_inventory = MountedInventory.find(params[:id])
  end

  # GET /mounted_inventories/new
  def new
    @mounted_inventory = MountedInventory.new
  end

  # GET /mounted_inventories/1/edit
  def edit
    @mounted_inventory = MountedInventory.find(params[:id])
  end

  # POST /mounted_inventories
  # POST /mounted_inventories.json
  def create
    @mounted_inventory = current_user.mounted_inventories.build(params[:mounted_inventory])
    @mounted_inventory.save
    respond_to do |format|
      if @mounted_inventory.save
        format.html { redirect_to :back, notice: 'A mounted inventory was successfully added.' }
        format.json { render action: 'show', status: :created, location: @mounted_inventory }
      else
        format.html { render action: 'new' }
        format.json { render json: @mounted_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mounted_inventories/1
  # PATCH/PUT /mounted_inventories/1.json
  def update
    respond_to do |format|
      if @mounted_inventory.update(params[:mounted_inventory])
        format.html { redirect_to @mounted_inventory, notice: 'A mounted inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mounted_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mounted_inventories/1
  # DELETE /mounted_inventories/1.json
  def destroy
    @mounted_inventory.destroy
    respond_to do |format|
      format.html { redirect_to mounted_inventories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mounted_inventories_helper.rb
module MountedInventoriesHelper
end

app/helpers/mounted_inventory_helper.rb
module MountedInventoryHelper
end

app/views/mounted_inventories/_form.html.erb
<%= form_for(@mounted_inventory) do |f| %>
  <% if @mounted_inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mounted_inventory.errors.count, "error") %> prohibited this mounted_inventory from being saved:</h2>

      <ul>
      <% @mounted_inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lot_number %><br />
    <%= f.text_field :lot_number %>
  </div>
  <div class="field">
    <%= f.label :total_mg %><br />
    <%= f.number_field :total_mg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mounted_inventories/edit.html.erb
<h1>Editing Mounted Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @mounted_inventory %> |
<%= link_to 'Back', mounted_inventories_path %>

app/views/mounted_inventories/index.html.erb
<h1><%= link_to "Mounted Inventory", mounted_inventories_path, :style => "text-decoration:underline; color:black;" %> / <%= link_to "Current Inventory", inventory_checks_path, :style => "color:black;" %></h1>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Lot number</th>
    <th>Total mg</th>
    <th>User</th>
    <th>Creation Date</th>
  </tr>

  <% @mounted_inventories.each do |mounted_inventory| %>
    <tr>
      <td><%= mounted_inventory.lot_number %></td>
      <td><%= mounted_inventory.total_mg %></td>
      <td><%= mounted_inventory.user.last_name %></td>
      <td><%= mounted_inventory.created_at.strftime("%B %d - %I:%M %p") %></td>
      <!-- td><%#= link_to 'Show', mounted_inventory %></td>
      <td><%#= link_to 'Edit', edit_mounted_inventory_path(mounted_inventory) %></td>
      <td><%#= link_to 'Destroy', mounted_inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
    </tr>
  <% end %>
  <%= simple_form_for(@mounted_inventory) do |f| %>
    <% if @mounted_inventory.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@mounted_inventory.errors.count, "error") %> prohibited this inventory check from being saved:</h2>

        <ul>
        <% @mounted_inventory.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div id="mounted_inventory_inputs">
      <tr>
        
        <td><%= f.input :lot_number %></td>
        <td><%= f.input :total_mg %></td>
        <td><%= f.input :user_id, disabled: true, placeholder: current_user.name %></td>
        <!-- <td><%#= f.input :created_at, disabled: true, placeholder: Time.now %></td> -->
        <td><%= f.submit 'Save', :class => "btn btn-primary", :hidefocus => true %></td>
      </tr>
    </div>
  <% end %>
</table>

<br />

<%= link_to 'New Mounted inventory', new_mounted_inventory_path %>

<script type="text/javascript">
  $('label').hide();
  </script>

app/views/mounted_inventories/new.html.erb
<h1>New mounted_inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', mounted_inventories_path %>

app/views/mounted_inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lot number:</b>
  <%= @mounted_inventory.lot_number %>
</p>

<p>
  <b>Total mg:</b>
  <%= @mounted_inventory.total_mg %>
</p>


<%= link_to 'Edit', edit_mounted_inventory_path(@mounted_inventory) %> |
<%= link_to 'Back', mounted_inventories_path %>