config/routes.rb
GhInventoryTracker::Application.routes.draw do
  resources :mounted_inventories

  root :to => "inventory_checks#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :inventory_checks

  
  
  devise_for :users
  ActiveAdmin.routes(self)

  devise_scope :users do
    get "login",    to: "devise/sessions#new"
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
  end

 
end

app/models/inventory_check.rb
class InventoryCheck < ActiveRecord::Base
	attr_accessible :user_id, :beginning_or_end, :shift, :forty_mg_lot_number, 
	:forty_mg_box_inventory, :forty_mg_bottle_inventory, :forty_mg_open_bottle_inventory, 
	:forty_mg_tablet_count, :forty_mg_total_inventory, :five_mg_lot_number, 
	:five_mg_box_inventory, :five_mg_bottle_inventory, :five_mg_open_bottle_inventory, 
	:five_mg_tablet_count, :five_mg_total_inventory, :total_inventory_count, :total_five_milligram_count, :total_forty_milligram_count

	before_validation :sum_milligram_totals

	belongs_to :user
	

	validates_presence_of :user_id, :forty_mg_lot_number, 
	:forty_mg_box_inventory, :forty_mg_bottle_inventory, :forty_mg_open_bottle_inventory, 
	:forty_mg_tablet_count, :forty_mg_total_inventory, :five_mg_lot_number, 
	:five_mg_box_inventory, :five_mg_bottle_inventory, :five_mg_open_bottle_inventory, 
	:five_mg_tablet_count, :five_mg_total_inventory, :total_inventory_count, :total_five_milligram_count, :total_forty_milligram_count


	def calculate_forty_mg_tablet_total
		((self.forty_mg_box_inventory * 600) + (self.forty_mg_bottle_inventory * 100) + self.forty_mg_open_bottle_inventory)
	end

	def calculate_five_mg_tablet_total
		((self.five_mg_box_inventory * 600) + (self.five_mg_bottle_inventory * 100) + self.five_mg_open_bottle_inventory)
	end

	def calculate_forty_mg_milligram_total
		((self.forty_mg_box_inventory * 600) + (self.forty_mg_bottle_inventory * 100) + self.forty_mg_open_bottle_inventory) * 40
	end

	def calculate_five_mg_milligram_total
		((self.five_mg_box_inventory * 600) + (self.five_mg_bottle_inventory * 100) + self.five_mg_open_bottle_inventory) * 5
	end

	def calculate_tablets_total
		calculate_forty_mg_tablet_total + calculate_five_mg_tablet_total
	end

	def sum_milligram_totals
		self.total_five_milligram_count = calculate_five_mg_milligram_total

		self.total_forty_milligram_count = calculate_forty_mg_milligram_total

		self.forty_mg_tablet_count = calculate_forty_mg_tablet_total

		self.five_mg_tablet_count = calculate_five_mg_tablet_total

		self.forty_mg_total_inventory = calculate_forty_mg_tablet_total
 
		self.five_mg_total_inventory = calculate_five_mg_tablet_total

		self.total_inventory_count = calculate_tablets_total
	end

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |inventory_check|
	      csv << inventory_check.attributes.values_at(*column_names)
	    end
	  end
	end


end

app/controllers/inventory_checks_controller.rb
class InventoryChecksController < ApplicationController
  before_filter :authenticate_user!
  # before_action :set_inventory_check, only: [:show, :edit, :update, :destroy]

  # GET /inventory_checks
  # GET /inventory_checks.json
  def index
    @inventory_checks = InventoryCheck.all
    @inventory_check = InventoryCheck.new
    respond_to do |format|
      format.html
      format.csv { send_data InventoryCheck.to_csv }
      format.xls { send_data InventoryCheck.to_csv(col_sep: "\t") }
    end
  end

  # GET /inventory_checks/1
  # GET /inventory_checks/1.json
  def show
    @inventory_check = InventoryCheck.find(params[:id])
  end

  # GET /inventory_checks/new
  def new
    @inventory_check = InventoryCheck.new
  end

  # GET /inventory_checks/1/edit
  def edit
    @inventory_check = InventoryCheck.find(params[:id])
  end

  # POST /inventory_checks
  # POST /inventory_checks.json
  def create
    @inventory_check = current_user.inventory_checks.build(params[:inventory_check])
    @inventory_check.save
    respond_to do |format|
      if @inventory_check.save
        format.html { redirect_to :back, notice: 'Inventory check was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inventory_check }
      else
        format.html { render action: 'new' }
        format.json { render json: @inventory_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_checks/1
  # PATCH/PUT /inventory_checks/1.json
  def update
    respond_to do |format|
      if @inventory_check.update(params[:inventory_check])
        format.html { redirect_to @inventory_check, notice: 'Inventory check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inventory_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_checks/1
  # DELETE /inventory_checks/1.json
  def destroy
    @inventory_check.destroy
    respond_to do |format|
      format.html { redirect_to inventory_checks_url }
      format.json { head :no_content }
    end
  end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_inventory_check
  #     @inventory_check = InventoryCheck.find(params[:id])
  #   end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def inventory_check_params
  #     params[:inventory_check]
  #   end
end

app/views/inventory_checks/_form.html.erb
<table>
  <tr>
    <th>Begin or End?</th>
    <th>Shift</th>
    <th>40mg Lot #</th>
    <th>40mg Unopened Box Count - (6 bottle per box)</th>
    <th>40mg Unopened Bottle Count - (100 Tablets per bottle)</th>
    <th>Current Open Bottle - 40mg Tablet Count - (Tablets left in open bottle)</th>
    <th>Total 40mg to date</th>
    <th></th>
    <th>5mg Lot #</th>
    <th>5mg Unopened Bottle Count - (100 Tablets per bottle)</th>
    <th>Current Open Bottle - 5mg Tablet Count - (Tablets left in open bottle)</th>
    <th>Total 5mg to date</th>
    <th></th>
    <th>Total Tablets To Date (40mg Tablets + 5mg Tablets)</th>
  </tr>
  
  <%= simple_form_for(@inventory_check) do |f| %>
    <% if @inventory_check.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@inventory_check.errors.count, "error") %> prohibited this inventory_check from being saved:</h2>

        <ul>
        <% @inventory_check.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div id="inventory_check_inputs">
      <tr>
        <td><%= f.input :user_id %></td>
        <td><%= f.input :beginning_or_end %></td>
        <td><%= f.input :shift %></td>
        <td><%= f.input :forty_mg_lot_number %></td>
        <td><%= f.input :forty_mg_box_inventory %></td>
        <td><%= f.input :forty_mg_bottle_inventory %></td>
        <td><%= f.input :forty_mg_open_bottle_inventory %></td>
        <td><%= f.input :forty_mg_tablet_count %></td>
        <td><%= f.input :forty_mg_total_inventory %></td>
        <td><%= f.input :five_mg_lot_number %></td>
        <td><%= f.input :five_mg_box_inventory %></td>
        <td><%= f.input :five_mg_bottle_inventory %></td>
        <td><%= f.input :five_mg_open_bottle_inventory %></td>
        <td><%= f.input :five_mg_tablet_count %></td>
        <td><%= f.input :five_mg_total_inventory %></td>
      </tr>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</table>

app/views/inventory_checks/edit.html.erb
<h1>Editing inventory_check</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_check %> |
<%= link_to 'Back', inventory_checks_path %>

app/views/inventory_checks/index.html.erb
<h1 id="title"><%= link_to "Current Inventory", inventory_checks_path, :style => "text-decoration:underline; color:black;" %> / <%= link_to "Mounted Inventory", mounted_inventories_path, :style => "color:black;" %></h1>
<table id="methadone-main-table" class="table table-striped table-bordered table-condensed">
  <tr>
    <th>User</th>
    <!-- <th>Beginning or Ending Shift?</th> -->
    <th>Created At</th>

    <th>40mg Lot #</th>
    <th>40mg Unopened Box Count - (6 bottle per box)</th>
    <th>40mg Unopened Bottle Count - (100 Tablets per bottle)</th>
    <th>Current Open Bottle - 40mg Tablet Count - (Tablets left in open bottle)</th>
    <th>Total 40mg Tablet Count in Lot</th>
    <th>Total 40mg Milligrams</th>
    <th>Total 40mg to date</th>


    <th>5mg Lot #</th>
    <th>5mg Unopened Box Count - (100 Tablets per bottle)</th>
    <th>5mg Unopened Bottle Count - (100 Tablets per bottle)</th>
    <th>Current Open Bottle - 5mg Tablet Count - (Tablets left in open bottle)</th>
    <th>Total 5mg Tablet Count in Lot</th>
    <th>Total 5mg Milligrams</th>
    <th>Total 5mg to date</th>

    <th>Total Tablets To Date (40mg Tablets + 5mg Tablets)</th>
  </tr>
<div class="table-data">
  <% @inventory_checks.each do |inventory_check| %>
    <tr>
      <td><%= inventory_check.user.name %></td>
      
      <td><%= inventory_check.created_at.strftime("%B %d - %I:%M %p") %></td>
      
      <td><%= inventory_check.forty_mg_lot_number %></td>
      <td><%= inventory_check.forty_mg_box_inventory %></td>
      <td><%= inventory_check.forty_mg_bottle_inventory %></td>
      <td><%= inventory_check.forty_mg_open_bottle_inventory %></td>
      <td><%= inventory_check.forty_mg_tablet_count %></td>
      <td><%= inventory_check.total_forty_milligram_count %></td>
      <td><%= inventory_check.forty_mg_total_inventory %></td>

      <td><%= inventory_check.five_mg_lot_number %></td>
      <td><%= inventory_check.five_mg_box_inventory %></td>
      <td><%= inventory_check.five_mg_bottle_inventory %></td>
      <td><%= inventory_check.five_mg_open_bottle_inventory %></td>
      <td><%= inventory_check.five_mg_tablet_count %></td>
      <td><%= inventory_check.total_five_milligram_count %></td>
      <td><%= inventory_check.five_mg_total_inventory %></td>

      <td><%= inventory_check.total_inventory_count %></td>
    </tr>
  <% end %>
</div>
  <%= simple_form_for(@inventory_check) do |f| %>
    <% if @inventory_check.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@inventory_check.errors.count, "error") %> prohibited this inventory check from being saved:</h2>

        <ul>
        <% @inventory_check.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div id="inventory_check_inputs">
      <tr>
        <td><%= f.input :user_id, disabled: true, placeholder: current_user.name %></td>
        
        <td><%= f.input :shift, :collection => ["AM", "PM"], disabled: true %></td>

        <td><%= f.input :forty_mg_lot_number %></td>
        <td><%= f.input :forty_mg_box_inventory %></td>
        <td><%= f.input :forty_mg_bottle_inventory %></td>
        <td><%= f.input :forty_mg_open_bottle_inventory, as: :float %></td>
        <td><%= f.input :forty_mg_tablet_count, disabled: true %></td>
        <td><%= f.input :total_forty_milligram_count, disabled: true %></td>
        <td><%= f.input :forty_mg_total_inventory, disabled: true %></td>

        <td><%= f.input :five_mg_lot_number %></td>
        <td><%= f.input :five_mg_box_inventory %></td>
        <td><%= f.input :five_mg_bottle_inventory %></td>
        <td><%= f.input :five_mg_open_bottle_inventory, as: :float %></td>
        <td><%= f.input :five_mg_tablet_count, disabled: true %></td>
        <td><%= f.input :five_mg_total_inventory, disabled: true %></td>
        <td><%= f.input :total_five_milligram_count, disabled: true %></td>
        <td><%= f.input :total_inventory_count, disabled: true %></td>
        <td>
          <%= f.submit 'Save', :class => "btn btn-primary", :hidefocus => true %>
        </td>
      </tr>
    </div>
</table>
    
<% end %>

  <script type="text/javascript">
  $('label').hide();
  </script>

app/views/inventory_checks/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Log ID</Data></Cell>
        <Cell><Data ss:Type="String">Created By</Data></Cell>
        <Cell><Data ss:Type="String">Created At</Data></Cell>
        <Cell><Data ss:Type="String">40mg Lot #</Data></Cell>
        <Cell><Data ss:Type="String">40mg Unopened Box Count - (6 bottle per box)</Data></Cell>
        <Cell><Data ss:Type="String">40mg Unopened Bottle Count - (100 Tablets per bottle)</Data></Cell>
        <Cell><Data ss:Type="String">Current Open Bottle - 40mg Tablet Count - (Tablets left in open bottle)</Data></Cell>
        <Cell><Data ss:Type="String">Total 40mg Tablet Count in Lot</Data></Cell>
        <Cell><Data ss:Type="String">Total 40mg Milligrams</Data></Cell>
        <Cell><Data ss:Type="String">Total 40mg to Date</Data></Cell>

        <Cell><Data ss:Type="String">5mg Lot #</Data></Cell>
        <Cell><Data ss:Type="String">5mg Unopened Box Count - (100 Tablets per bottle)</Data></Cell>
        <Cell><Data ss:Type="String">5mg Unopened Bottle Count - (100 Tablets per bottle)</Data></Cell>
        <Cell><Data ss:Type="String">Current Open Bottle - 5mg Tablet Count - (Tablets left in open bottle)</Data></Cell>
        <Cell><Data ss:Type="String">Total 5mg Tablet Count in Lot</Data></Cell>
        <Cell><Data ss:Type="String">Total 5mg Milligrams</Data></Cell>
        <Cell><Data ss:Type="String">Total 5mg to Date</Data></Cell>

        <Cell><Data ss:Type="String">Total Tablets To Date (40mg Tablets + 5mg Tablets)</Data></Cell>
      </Row>
    <% @inventory_checks.each do |inventory_check| %>
      <Row>
        <Cell><Data ss:Type="String"><%= inventory_check.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.created_at.strftime("%B %d - %I:%M %p") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.forty_mg_lot_number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.forty_mg_box_inventory %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.forty_mg_bottle_inventory %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.forty_mg_open_bottle_inventory %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.forty_mg_tablet_count %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.total_forty_milligram_count %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.forty_mg_total_inventory %></Data></Cell>

        <Cell><Data ss:Type="String"><%= inventory_check.five_mg_lot_number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.five_mg_box_inventory %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.five_mg_bottle_inventory %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.five_mg_open_bottle_inventory %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.five_mg_tablet_count %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.total_five_milligram_count %></Data></Cell>
        <Cell><Data ss:Type="String"><%= inventory_check.five_mg_total_inventory %></Data></Cell>

        <Cell><Data ss:Type="String"><%= inventory_check.total_inventory_count %></Data></Cell>

      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/inventory_checks/new.html.erb
<h1>New inventory_check</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_checks_path %>

app/views/inventory_checks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inventory_check_path(@inventory_check) %> |
<%= link_to 'Back', inventory_checks_path %>